describe('Edit user', function () {
    before('login', () => {
        cy.visit("https://portal.digihcs.com/lun/login")
        cy.wait(1000)
        cy.get('input[id="normal_login_username"]')
            .should('be.visible')
            .clear()
            .type('superadmin')
            .should('have.value', 'superadmin')
        cy.get('input[id="normal_login_password"')
            .should('be.visible')
            .clear()
            .type('12345678')
            .should('have.value', '12345678')
        cy.get('button[htmltype="submit"]')
            .click()
        cy.randomStr('w{5}').as('passwordUpdate')
        cy.randomStr('w{5}').as('fullnameUpdate')
    })
    beforeEach('restoreToken', () => {
        cy.restoreLocalStorageCache()
    })
    afterEach('saveToken', () => {
        cy.saveLocalStorageCache()
    })
    it('Mở modal sửa user', function () {
        cy.contains('USER')
            .click()
        cy.get(".erp-grid-container", { timeout: 30000 }).should("be.visible")
        cy.get('button[name="btnEditUser"]')
            .first()
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('button.cancel-btn')
            .should('be.visible')
        cy.get('button.ok-btn')
            .should('be.visible')
    })
    it('Không thể sửa user cho đến khi nhập đủ trường', function () {
        cy.get('input[id="createUserForm_password"]')
            .should('be.visible')
            .clear()
            .type(this.passwordUpdate)
            .should('have.value', this.passwordUpdate)
        cy.get('button.ok-btn')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .scrollIntoView()
            .should('be.visible')
        cy.get('input[id="createUserForm_confirm"]')
            .clear()
            .type(this.passwordUpdate)
            .should('have.value', this.passwordUpdate)
        cy.get('input[id="createUserForm_fullName"]')
            .clear()
        cy.get('button.ok-btn')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .scrollIntoView()
            .should('be.visible')
        cy.get('input[id="createUserForm_fullName"]')
            .clear()
            .type(this.fullnameUpdate)
            .should('have.value', this.fullnameUpdate)
        cy.get('button.ok-btn')
            .click()
        cy.get('div[class="innos-ui-translate-notification-notice-content"]')
            .contains('User is updated')
    })
    it('Đóng modal', function () {
        cy.get('button[name="add"]')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('button.innos-ui-modal-close')
            .should('be.visible')
            .click()
        cy.get(".erp-grid-container")
            .should("be.visible")
        cy.get('button[name="add"]')
            .click()
        cy.get('button.cancel-btn')
            .should('be.visible')
            .click()
        cy.get(".erp-grid-container")
            .should("be.visible")
    })

})