describe('Add new user', function () {
    before('login', () => {
        cy.visit("https://portal.digihcs.com/lun/login")
        cy.wait(1000)
        cy.get('input[id="normal_login_username"]')
            .should('be.visible')
            .clear()
            .type('superadmin')
            .should('have.value', 'superadmin')
        cy.get('input[id="normal_login_password"')
            .should('be.visible')
            .clear()
            .type('12345678')
            .should('have.value', '12345678')
        cy.get('button[htmltype="submit"]')
            .click()
        cy.randomStr('w{5}').as('username')
        cy.randomStr('w{5}').as('password')
        cy.randomStr('w{5} w{5} w{5}').as('fullname')
    })
    beforeEach('restoreToken', () => {
        cy.restoreLocalStorageCache()
    })
    afterEach('saveToken', () => {
        cy.saveLocalStorageCache()
    })
    it('Mở modal thêm user', function () {
        cy.contains('USER')
            .click()
        cy.get(".erp-grid-container", { timeout: 30000 }).should("be.visible")
        cy.get('button[name="add"]')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('button')
            .contains('Add')
            .should('be.visible')
    })
    it('Không thể thêm user cho đến khi nhập đủ trường', function () {
        cy.get('input[id="createUserForm_username"]')
            .should('be.visible')
            .clear()
            .type(this.username)
            .should('have.value', this.username)
        cy.get('button')
            .contains('Add')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('input[id="createUserForm_password"]')
            .clear()
            .type(this.password)
            .should('have.value', this.password)
        cy.get('button')
            .contains('Add')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('input[id="createUserForm_confirm"]')
            .clear()
            .type(this.password)
            .should('have.value', this.password)
        cy.get('button')
            .contains('Add')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('input[id="createUserForm_fullName"]')
            .clear()
            .type(this.fullname)
            .should('have.value', this.fullname)
        cy.get('div.innos-ui-form-item')
            .contains('Phòng Phần Mềm')
            .parent()
            .parent()
            .find('button')
            .contains('User')
            .click()
        cy.get('button.ok-btn')
            .click()
        cy.get('div[class="innos-ui-translate-notification-notice-content"]')
            .contains('User is added')
    })
    // it('Kiểm tra grid cập nhật', function () {
    //     cy.get(".erp-grid-container", { timeout: 30000 })
    //         .should("be.visible")
    //     cy.get('div[ref="ePinnedLeftHeader"]')
    //         .find('input.ag-floating-filter-input')
    //         .first()
    //         .type(this.fullname)
    //     cy.get('div.ag-body-viewport')
    //         .contains(this.fullname)
    //         .should('be.visible')
    // })
    it('Đóng modal', function () {
        cy.get('button[name="add"]')
            .click()
        cy.get('div[id="rcDialogTitle0"]')
            .should('be.visible')
        cy.get('button.innos-ui-modal-close')
            .should('be.visible')
            .click()
        cy.get(".erp-grid-container")
            .should("be.visible")
        cy.get('button[name="add"]')
            .click()
        cy.get('button.cancel-btn')
            .should('be.visible')
            .click()
        cy.get(".erp-grid-container")
            .should("be.visible")
    })

})